version: '3'
services:
  database:
    image: postgres
    ports:
    - 6432:5432
    environment:
      POSTGRES_DB: themyscira
      POSTGRES_USER: themyscira
      POSTGRES_PASSWORD: themyscira
  service:
    build: .
    ports:
    - 9090:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/themyscira
      SPRING_DATASOURCE_USERNAME: themyscira
      SPRING_DATASOURCE_PASSWORD: themyscira
    depends_on:
    - database